# name: Python application
 
# on:
#   push:
#     branches: [ pipeline ]
 
# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     needs: deploy
#     name: Run Robot Framework Tests
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Create folder for reports
#         run: mkdir reports
#       - name: Robot Framework Test
#         # NOTE: joonvena/robotframework-docker-action@v0.1 had permissions issue
#         # This action is based on a Docker image. I had to fall back to that image
#         # and use --user flag
#         run: |
#           docker run \
#             -v ${PWD}/reports:/opt/robotframework/reports:Z \
#             -v $/tests_e2e:/opt/robotframework/tests:Z \
#             --user $(id -u):$(id -g) \
#             -e BROWSER=chrome \
#             ppodgorsek/robot-framework:latest
#       - name: Upload test results
#         uses: actions/upload-artifact@v1
#         if: always()
#         with:
#           name: robotframework report
#           path: reports

      

name: Publish Python Package

on:
  push:
    branches: [ pipeline ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v3
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}